"""Configuration module for query processing package."""

from .settings import (
    # Configuration class and instance
    Config, config,

    # Client types
    CLIENT_DEEPSEEK, CLIENT_OPENAI, CLIENT_OPENROUTER, CLIENT_GEMINI,
    SUPPORTED_CHAT_CLIENTS, SUPPORTED_EMBED_CLIENTS,

    # API URLs
    DEEPSEEK_API_URL, OPENAI_API_URL, OPENROUTER_API_URL,

    # Model names
    MODEL_DEEPSEEK_CHAT, MODEL_DEEPSEEK_REASONER,
    MODEL_GPT4O, MODEL_GPT4O_MINI, MODEL_OPENROUTER_DEFAULT, MODEL_GEMINI_DEFAULT,
    DEFAULT_CHAT_MODELS, DEFAULT_EMBED_MODELS,

    # File paths
    NODES_FILE, EDGES_FILE, PRIOR_MATRIX_FILE,

    # Function schemas
    QUERY_PARSE_FUNCTION_SCHEMA,

    # Default parameters
    DEFAULT_LLM_ATTEMPTS, DEFAULT_TEMPERATURE, DEFAULT_MAX_TOKENS,
    DEFAULT_PROCESSOR_PARAMS,

    # Retrieval configuration
    TOP_K_ENTITIES, TOP_K_RELATED, SIMILARITY_THRESHOLD,

    # Error messages
    ERROR_INVALID_CHAT_CLIENT, ERROR_INVALID_EMBED_CLIENT,
    ERROR_GRAPH_FILE_NOT_FOUND, ERROR_INVALID_JSON,

    # Success messages
    SUCCESS_GRAPH_LOADED, SUCCESS_CLIENT_INITIALIZED,
)

__all__ = [
    'Config', 'config',
    'CLIENT_DEEPSEEK', 'CLIENT_OPENAI', 'CLIENT_OPENROUTER', 'CLIENT_GEMINI',
    'SUPPORTED_CHAT_CLIENTS', 'SUPPORTED_EMBED_CLIENTS',
    'DEEPSEEK_API_URL', 'OPENAI_API_URL', 'OPENROUTER_API_URL',
    'MODEL_DEEPSEEK_CHAT', 'MODEL_DEEPSEEK_REASONER',
    'MODEL_GPT4O', 'MODEL_GPT4O_MINI', 'MODEL_OPENROUTER_DEFAULT', 'MODEL_GEMINI_DEFAULT',
    'DEFAULT_CHAT_MODELS', 'DEFAULT_EMBED_MODELS',
    'NODES_FILE', 'EDGES_FILE', 'PRIOR_MATRIX_FILE',
    'QUERY_PARSE_FUNCTION_SCHEMA',
    'DEFAULT_LLM_ATTEMPTS', 'DEFAULT_TEMPERATURE', 'DEFAULT_MAX_TOKENS',
    'DEFAULT_PROCESSOR_PARAMS',
    'TOP_K_ENTITIES', 'TOP_K_RELATED', 'SIMILARITY_THRESHOLD',
    'ERROR_INVALID_CHAT_CLIENT', 'ERROR_INVALID_EMBED_CLIENT',
    'ERROR_GRAPH_FILE_NOT_FOUND', 'ERROR_INVALID_JSON',
    'SUCCESS_GRAPH_LOADED', 'SUCCESS_CLIENT_INITIALIZED',
]
